### ISSUE TITLE
Informative error messages for Try-assertions

### ISSUE THREAD

**Issue by tvrg** [assertj/assertj-vavr#65]
In case of failure the assertion
```java
Try<Void> result = someFunction();
VavrAssertions.assertThat(result).isSuccess();
```
outputs
```
java.lang.AssertionError: 
Expecting Try to be a Success, but wasn't
```
Most of the time I need to know exactly what went wrong. It would be great if the error message contains a summary of the thrown exception. I'm thinking of its name, message, and stack trace.

What do you think about that?

**Comment by mchmielarz** [comment]
Well, the message is the text you can see in the output. The error thrown is of `AssertionError` instance.

The only thing I miss in the output are parts of the stack trace related to assertj. Is this what you were thinking about?

If it is not, could you paste a more detailed example of what you would expect in the output in a case of error?

**Comment by jqno** [comment]
I'm not the OP, but I ran into this as well.

If a `Try` is not a `Success`, it must be a `Failure`, and in that case it has an exception with a stacktrace and possibly a message.

If I expect a `Success` but it's a `Failure` instead, it's super useful to see the exception inside the `Failure`, because that makes it so much easier to track down what went wrong.

Now I have to add a print statement or some boilerplate code to find out what the exception was, which defeats the purpose of the nice AssertJ assertions.

**Comment by mchmielarz** [comment]
Oh, right. Having that would be truly useful. Thank you for explanation
